### PR TITLE
more metal hex spacers

### PR DESCRIPTION
**Pull request by iaakki**

### CODE REVIEW

**Comment by iaakki** [comment]
Oh yes.. Maybe @freezy can fiddle the materials too?

**Comment by freezy** [comment]
Which ones did you add? 1-5/16" onwards?

**Comment by iaakki** [comment]
Yes probably that was it. 😊

**Comment by iaakki** [comment]
I trust you. I have no idea how to verify these material changes properly. Just merge in when you please. 😘

**Comment by freezy** [comment]
Can you pull my updates and check if they all appear in the asset library?

image

**Pull request merged**
